apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: nvidia-gpu-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-gpu-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-gpu-device-plugin
    spec:
      priorityClassName: system-node-critical
      nodeSelector:
        kubernetes.io/os: linux
        feature.node.kubernetes.io/pci-10de.present: "true"
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: nvidia-install-dir-host
        hostPath:
          path: /opt/nvidia-driver
      - name: dev
        hostPath:
          path: /dev
      initContainers:
      - image: "virtuozzo/nvidia-driver-installer:39-6.6.13-200.fc39.x86_64-550.107.02"
        imagePullPolicy: IfNotPresent
        name: nvidia-driver-installer
        resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true
        volumeMounts:
        - name: nvidia-install-dir-host
          mountPath: /opt/nvidia-host
        - name: dev
          mountPath: /dev
      containers:
      - image: "registry.k8s.io/nvidia-gpu-device-plugin@sha256:ebd0d26fb21ae9c7d11da156737006ceff085029c697a3a163774188c3328dbe"
        command: ["/usr/bin/nvidia-gpu-device-plugin", "-logtostderr", "-host-path=/opt/nvidia-driver"]
        name: nvidia-gpu-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 10Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /device-plugin
        - name: dev
          mountPath: /dev
  updateStrategy:
    type: RollingUpdate
